include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Often unnecessary.
    use_key_in_widget_constructors: false

    # For closures.
    prefer_function_declarations_over_variables: false

formatter:
  page_width: 100
