//The TITLE values must be at the end
enum MediaSort {
  TRENDING,
  TRENDING_DESC,
  POPULARITY,
  POPULARITY_DESC,
  SCORE,
  SCORE_DESC,
  START_DATE,
  START_DATE_DESC,
  END_DATE,
  END_DATE_DESC,
  TITLE_ROMAJI,
  TITLE_ROMAJI_DESC,
  TITLE_ENGLISH,
  TITLE_ENGLISH_DESC,
  TITLE_NATIVE,
  TITLE_NATIVE_DESC,
}
